CREATE TABLE xxl_job_group (
                               id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               app_name varchar(64) NOT NULL,
                               title varchar(128) NOT NULL,
                               address_type smallint NOT NULL DEFAULT 0,
                               address_list text,
                               update_time timestamp
);

CREATE TABLE xxl_job_registry (
                                  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  registry_group varchar(50) NOT NULL,
                                  registry_key varchar(255) NOT NULL,
                                  registry_value varchar(255) NOT NULL,
                                  update_time timestamp,
                                  CONSTRAINT xxl_job_registry_i_g_k_v UNIQUE (registry_group, registry_key, registry_value)
);

CREATE TABLE xxl_job_info (
                              id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              job_group integer NOT NULL,
                              job_desc varchar(255) NOT NULL,
                              add_time timestamp,
                              update_time timestamp,
                              author varchar(64),
                              alarm_email varchar(255),
                              schedule_type varchar(50) NOT NULL DEFAULT 'NONE',
                              schedule_conf varchar(128),
                              misfire_strategy varchar(50) NOT NULL DEFAULT 'DO_NOTHING',
                              executor_route_strategy varchar(50),
                              executor_handler varchar(255),
                              executor_param varchar(512),
                              executor_block_strategy varchar(50),
                              executor_timeout integer NOT NULL DEFAULT 0,
                              executor_fail_retry_count integer NOT NULL DEFAULT 0,
                              glue_type varchar(50) NOT NULL,
                              glue_source text,
                              glue_remark varchar(128),
                              glue_updatetime timestamp,
                              child_jobid varchar(255),
                              trigger_status smallint NOT NULL DEFAULT 0,
                              trigger_last_time bigint NOT NULL DEFAULT 0,
                              trigger_next_time bigint NOT NULL DEFAULT 0
);

CREATE TABLE xxl_job_logglue (
                                 id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 job_id integer NOT NULL,
                                 glue_type varchar(50),
                                 glue_source text,
                                 glue_remark varchar(128) NOT NULL,
                                 add_time timestamp,
                                 update_time timestamp
);

CREATE TABLE xxl_job_log (
                             id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             job_group integer NOT NULL,
                             job_id integer NOT NULL,
                             executor_address varchar(255),
                             executor_handler varchar(255),
                             executor_param varchar(512),
                             executor_sharding_param varchar(20),
                             executor_fail_retry_count integer NOT NULL DEFAULT 0,
                             trigger_time timestamp,
                             trigger_code integer NOT NULL,
                             trigger_msg text,
                             handle_time timestamp,
                             handle_code integer NOT NULL,
                             handle_msg text,
                             alarm_status smallint NOT NULL DEFAULT 0
);

CREATE INDEX i_trigger_time ON xxl_job_log (trigger_time);
CREATE INDEX i_handle_code ON xxl_job_log (handle_code);
CREATE INDEX i_jobid_jobgroup ON xxl_job_log (job_id, job_group);
CREATE INDEX i_job_id ON xxl_job_log (job_id);

CREATE TABLE xxl_job_log_report (
                                    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    trigger_day timestamp,
                                    running_count integer NOT NULL DEFAULT 0,
                                    suc_count integer NOT NULL DEFAULT 0,
                                    fail_count integer NOT NULL DEFAULT 0,
                                    update_time timestamp,
                                    CONSTRAINT xxl_job_log_report_i_trigger_day UNIQUE (trigger_day)
);

CREATE TABLE xxl_job_lock (
                              lock_name varchar(50) PRIMARY KEY
);

CREATE TABLE xxl_job_user (
                              id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              username varchar(50) NOT NULL,
                              password varchar(100) NOT NULL,
                              token varchar(100),
                              role smallint NOT NULL,
                              permission varchar(255),
                              CONSTRAINT xxl_job_user_i_username UNIQUE (username)
);