--
-- XXL-JOB PostgreSQL schema
--

CREATE TABLE xxl_job_group (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_name varchar(64) NOT NULL,
    title varchar(12) NOT NULL,
    address_type smallint NOT NULL DEFAULT 0,
    address_list text,
    update_time timestamp
);

CREATE TABLE xxl_job_registry (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registry_group varchar(50) NOT NULL,
    registry_key varchar(255) NOT NULL,
    registry_value varchar(255) NOT NULL,
    update_time timestamp,
    CONSTRAINT xxl_job_registry_i_g_k_v UNIQUE (registry_group, registry_key, registry_value)
);

CREATE TABLE xxl_job_info (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_group integer NOT NULL,
    job_desc varchar(255) NOT NULL,
    add_time timestamp,
    update_time timestamp,
    author varchar(64),
    alarm_email varchar(255),
    schedule_type varchar(50) NOT NULL DEFAULT 'NONE',
    schedule_conf varchar(128),
    misfire_strategy varchar(50) NOT NULL DEFAULT 'DO_NOTHING',
    executor_route_strategy varchar(50),
    executor_handler varchar(255),
    executor_param varchar(512),
    executor_block_strategy varchar(50),
    executor_timeout integer NOT NULL DEFAULT 0,
    executor_fail_retry_count integer NOT NULL DEFAULT 0,
    glue_type varchar(50) NOT NULL,
    glue_source text,
    glue_remark varchar(128),
    glue_updatetime timestamp,
    child_jobid varchar(255),
    trigger_status smallint NOT NULL DEFAULT 0,
    trigger_last_time bigint NOT NULL DEFAULT 0,
    trigger_next_time bigint NOT NULL DEFAULT 0
);

CREATE TABLE xxl_job_logglue (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id integer NOT NULL,
    glue_type varchar(50),
    glue_source text,
    glue_remark varchar(128) NOT NULL,
    add_time timestamp,
    update_time timestamp
);

CREATE TABLE xxl_job_log (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_group integer NOT NULL,
    job_id integer NOT NULL,
    executor_address varchar(255),
    executor_handler varchar(255),
    executor_param varchar(512),
    executor_sharding_param varchar(20),
    executor_fail_retry_count integer NOT NULL DEFAULT 0,
    trigger_time timestamp,
    trigger_code integer NOT NULL,
    trigger_msg text,
    handle_time timestamp,
    handle_code integer NOT NULL,
    handle_msg text,
    alarm_status smallint NOT NULL DEFAULT 0
);

CREATE INDEX i_trigger_time ON xxl_job_log (trigger_time);
CREATE INDEX i_handle_code ON xxl_job_log (handle_code);
CREATE INDEX i_jobid_jobgroup ON xxl_job_log (job_id, job_group);
CREATE INDEX i_job_id ON xxl_job_log (job_id);

CREATE TABLE xxl_job_log_report (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trigger_day timestamp,
    running_count integer NOT NULL DEFAULT 0,
    suc_count integer NOT NULL DEFAULT 0,
    fail_count integer NOT NULL DEFAULT 0,
    update_time timestamp,
    CONSTRAINT xxl_job_log_report_i_trigger_day UNIQUE (trigger_day)
);

CREATE TABLE xxl_job_lock (
    lock_name varchar(50) PRIMARY KEY
);

CREATE TABLE xxl_job_user (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar(50) NOT NULL,
    password varchar(100) NOT NULL,
    token varchar(100),
    role smallint NOT NULL,
    permission varchar(255),
    CONSTRAINT xxl_job_user_i_username UNIQUE (username)
);

INSERT INTO xxl_job_group (id, app_name, title, address_type, address_list, update_time)
VALUES
    (1, 'xxl-job-executor-sample', '通用执行器Sample', 0, NULL, now()),
    (2, 'xxl-job-executor-sample-ai', 'AI执行器Sample', 0, NULL, now());

INSERT INTO xxl_job_info (
    id,
    job_group,
    job_desc,
    add_time,
    update_time,
    author,
    alarm_email,
    schedule_type,
    schedule_conf,
    misfire_strategy,
    executor_route_strategy,
    executor_handler,
    executor_param,
    executor_block_strategy,
    executor_timeout,
    executor_fail_retry_count,
    glue_type,
    glue_source,
    glue_remark,
    glue_updatetime,
    child_jobid
)
VALUES
    (
        1,
        1,
        '示例任务01',
        now(),
        now(),
        'XXL',
        '',
        'CRON',
        '0 0 0 * * ? *',
        'DO_NOTHING',
        'FIRST',
        'demoJobHandler',
        '',
        'SERIAL_EXECUTION',
        0,
        0,
        'BEAN',
        '',
        'GLUE代码初始化',
        now(),
        ''
    ),
    (
        2,
        2,
        'Ollama示例任务01',
        now(),
        now(),
        'XXL',
        '',
        'NONE',
        '',
        'DO_NOTHING',
        'FIRST',
        'ollamaJobHandler',
        $json$
{
    "input": "慢SQL问题分析思路",
    "prompt": "你是一个研发工程师，擅长解决技术类问题。",
    "model": "qwen3:0.6b"
}
$json$,
        'SERIAL_EXECUTION',
        0,
        0,
        'BEAN',
        '',
        'GLUE代码初始化',
        now(),
        ''
    ),
    (
        3,
        2,
        'Dify示例任务',
        now(),
        now(),
        'XXL',
        '',
        'NONE',
        '',
        'DO_NOTHING',
        'FIRST',
        'difyWorkflowJobHandler',
        $json$
{
    "inputs": {
        "input": "查询班级各学科前三名"
    },
    "user": "xxl-job",
    "baseUrl": "http://localhost/v1",
    "apiKey": "app-OUVgNUOQRIMokfmuJvBJoUTN"
}
$json$,
        'SERIAL_EXECUTION',
        0,
        0,
        'BEAN',
        '',
        'GLUE代码初始化',
        now(),
        ''
    );

INSERT INTO xxl_job_user (id, username, password, role, permission)
VALUES (1, 'admin', '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92', 1, NULL);

INSERT INTO xxl_job_lock (lock_name)
VALUES ('schedule_lock');

SELECT setval(pg_get_serial_sequence('xxl_job_group', 'id'), COALESCE((SELECT MAX(id) FROM xxl_job_group), 1), true);
SELECT setval(pg_get_serial_sequence('xxl_job_info', 'id'), COALESCE((SELECT MAX(id) FROM xxl_job_info), 1), true);
SELECT setval(pg_get_serial_sequence('xxl_job_user', 'id'), COALESCE((SELECT MAX(id) FROM xxl_job_user), 1), true);
